# Generated by Django 6.0.7 on 2026-07-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autonomy_level',
            field=models.CharField(choices=[('read_only', 'Read-only'), ('full', 'Full (audited)')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='system_prompt',
            field=models.TextField(blank=True, help_text="Appended to Diabase's base prompt: project conventions, constraints, tone."),
        ),
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='workspaces.project')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_context_file_name_per_project')],
            },
        ),
    ]
