# Generated by Django 6.0.7 on 2026-07-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentconnection'),
        ('workspaces', '0003_project_autonomy_level_project_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='agents.agentconnection'),
        ),
    ]
