# Generated by Django 6.0.7 on 2026-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_project_agent_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('chat', 'Chat'), ('plan_result', 'Plan result')], default='chat', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='autonomy_level',
            field=models.CharField(choices=[('read_only', 'Read-only'), ('plan', 'Plan & approve'), ('full', 'Full (audited)')], default='plan', max_length=20),
        ),
    ]
