# Generated by Django 6.0.7 on 2026-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_turnevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('backend', models.CharField(choices=[('claude_code', 'Claude Code (subscription)'), ('anthropic_api', 'Anthropic API'), ('openai_compat', 'OpenAI-compatible endpoint')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('base_url', models.CharField(blank=True, max_length=300)),
                ('api_key_encrypted', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
