# Generated by Django 6.0.7 on 2026-07-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentconnection'),
        ('workspaces', '0005_chatmessage_kind_alter_project_autonomy_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=10)),
                ('decided_by', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('continuation_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.turn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='workspaces.project')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='agents.turn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.plan')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'order'), name='unique_step_order_per_plan')],
            },
        ),
    ]
