# Generated by Django 6.0.7 on 2026-07-21 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_plan_planstep'),
        ('workspaces', '0006_conversation_chatmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='workspaces.conversation'),
        ),
    ]
