# Generated by Django 6.0.7 on 2026-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_turn_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstep',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
