# Generated by Django 6.0.7 on 2026-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_planstep_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='boot_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
