# Generated by Django 6.0.7 on 2026-07-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0008_chatmessage_conversation_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('schema', 'Schema'), ('audit', 'Audit trail'), ('chat', 'Chat'), ('context', 'Context file')], max_length=10)),
                ('source_ref', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chunks', to='workspaces.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'source_type'], name='memory_memo_project_f07af5_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'source_type', 'source_ref'), name='unique_chunk_per_source')],
            },
        ),
    ]
