# Generated by Django 6.0.7 on 2026-08-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_turn_boot_id'),
        ('memory', '0001_initial'),
        ('workspaces', '0008_chatmessage_conversation_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('neo4j_uri', models.CharField(blank=True, max_length=300)),
                ('neo4j_user', models.CharField(blank=True, max_length=100)),
                ('neo4j_password_encrypted', models.TextField(blank=True, editable=False)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedder_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentconnection')),
                ('llm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentconnection')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ref', models.CharField(max_length=200)),
                ('episode_uuid', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_episodes', to='workspaces.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'source_ref'), name='unique_episode_per_source')],
            },
        ),
    ]
