# Generated by Django 6.0.7 on 2026-07-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("project_name", models.CharField(blank=True, max_length=100)),
                ("server_name", models.CharField(blank=True, max_length=100)),
                ("adapter_type", models.CharField(blank=True, max_length=20)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent"), ("system", "System")], max_length=10
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True, help_text="Username, or agent model identifier", max_length=200
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Tool name (execute_sql) or event slug (project.created)", max_length=100
                    ),
                ),
                ("payload_in", models.JSONField(blank=True, default=dict)),
                ("payload_out", models.JSONField(blank=True, default=dict)),
                (
                    "outcome",
                    models.CharField(choices=[("success", "Success"), ("error", "Error")], max_length=10),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
