# Generated by Django 6.0.7 on 2026-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_payload_days', models.PositiveIntegerField(default=0, help_text='Days to keep audit payloads; 0 keeps them forever')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'retention policy',
            },
        ),
        migrations.AddField(
            model_name='auditentry',
            name='redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
