# Generated by Django 6.0.7 on 2026-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("sqlite", "SQLite (local file)"),
                            ("postgres", "PostgreSQL / Supabase self-hosted"),
                            ("supabase", "Supabase Cloud (Management API)"),
                        ],
                        default="sqlite",
                        max_length=20,
                    ),
                ),
                (
                    "dsn",
                    models.CharField(
                        help_text="SQLite: path to the .db file — Postgres: postgresql://user:pass@host:5432/db — Supabase Cloud: project ref (token in SUPABASE_ACCESS_TOKEN)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
