# Generated by Django 6.0.7 on 2026-07-22 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeFunctionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('verify_jwt', models.BooleanField(default=True)),
                ('deployed_version', models.IntegerField(blank=True, null=True)),
                ('deployed_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_sources', to='instances.server')),
            ],
            options={
                'ordering': ['slug'],
                'constraints': [models.UniqueConstraint(fields=('server', 'slug'), name='unique_function_source_per_server')],
            },
        ),
    ]
